quiz/urls.py
from django.urls import path
from .views import (
    QuizListView,
    QuizReviewView,
    QuizResponsesView,
    QuizResponsesByRespondentView,
    QuizCreateView,
    QuizEditView,
    QuizDeleteView,
    QuizSubmittedView,
    take_quiz,
)

urlpatterns = [
    path('quiz/new/', QuizCreateView.as_view(), name='createnew'),
    path('dashboard/', QuizListView.as_view(), name='dashboard'),
    path('review/<uuid:pk>/', QuizReviewView.as_view(), name='quizreview'),
    path('responses/<uuid:pk>/', QuizResponsesView.as_view(), name='quizresponses'),
    path('respondents/<uuid:pk>/', QuizResponsesByRespondentView.as_view(), name='quizrespondents'),
    path('edit/<uuid:pk>/', QuizEditView.as_view(), name='quizedit'),
    path('delete/<uuid:pk>/', QuizDeleteView.as_view(), name='quizdelete'),
    path('take/<uuid:quiz_id>/', take_quiz, name='quiztake'),
    path('submitted/<uuid:pk>/', QuizSubmittedView.as_view(), name='quizsubmitted'),
]

quiz_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('controls/', admin.site.urls),
    path('', include('quiz.urls')),
    path('users/', include('users.urls')),
    path('users/', include('django.contrib.auth.urls')),
    path('', TemplateView.as_view(template_name="home.html"), name='home'),
]

quiz/models.py
import uuid
from django.db import models
from django.urls import reverse


class Quiz(models.Model):
    class Meta: 
        verbose_name = "Quiz"
        verbose_name_plural = "Quizzes"
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    title = models.CharField(max_length=200)
    author = models.ForeignKey(
        'users.CustomUser',
        on_delete=models.CASCADE,
    )
    date_created = models.DateTimeField(auto_now=True)
    directions_and_introductory_text = models.TextField(max_length=5000)
    primary_source_text = models.TextField(max_length=20000)
    message = models.TextField(max_length=2000, blank=True)

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse('quizreview', args=[str(self.id)])

class Question(models.Model):
    quiz = models.ForeignKey(
        Quiz,
        on_delete=models.CASCADE,
    )
    question_text = models.TextField(max_length=2000, blank=True)
    notes_for_question = models.TextField(max_length=6000, blank=True)
    

    def __str__(self):
        return self.quiz.title[:50] + ": " + self.question_text[:50]

class QuizResponse(models.Model):
    quiz = models.ForeignKey(
        Quiz,
        on_delete=models.CASCADE,
    )
    id_number = models.IntegerField()
    name = models.CharField(max_length=100)
    attempt_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.quiz.title[:50] + ": " + self.name
    
    def get_absolute_url(self):
        return reverse('quizsubmitted', args=[str(self.quiz_id)])

class QuestionResponse(models.Model):
    quiz_response = models.ForeignKey(
        QuizResponse,
        on_delete=models.CASCADE,
    )
    question = models.ForeignKey(
        Question,
        on_delete=models.CASCADE,
    )
    response_text = models.TextField(max_length=6000, null=True)
 
    def __str__(self):
        return self.quiz_response.quiz.title[:50] + ": " + self.quiz_response.name + " on " + self.question.question_text[:50]

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- Bootstrap CSS -->
        <link rel="stylesheet"
        href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
        integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
        crossorigin="anonymous">

        <title>Quiz App</title>
        <link href="https://fonts.googleapis.com/css?family=Merriweather+Sans&display=swap" rel="stylesheet">
        <link href="{% static 'css/base.css' %}" rel="stylesheet">
    </head>
    <body>
        {% block nav %}
            <h1 class="card-title"><a href="{% url 'home' %}">Quiz App</a></h1>
            {% if user.is_authenticated %}
            <p class="card-text">Hi {{ user.username }}! | <a href="{% url 'dashboard' %}">View your quizzes</a> | <a href="{% url 'createnew' %}">+ New quiz</a> | <a href="{% url 'logout' %}">Log out</a></p>
            {% else %}
            <p class="card-text"><a href="{% url 'login' %}">Log in</a> or <a href="{% url 'signup' %}">sign up</a> to create and view your quizzes</p>
            {% endif %}
        {% endblock nav %} 
    <br> 
    <div>
        {% block content %}
        {% endblock content %}
    </div>
    
        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
        integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
        integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
        crossorigin="anonymous"></script>
    </body>
</html>

templates/createnew.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}

<div class="card" style="width: 55em;margin:0 auto;">
    <div class="card-header">
        <h1>Add New Quiz</h1>
    </div>
    <div class="card-body">
        <form action="" method="post">
            {% csrf_token %}
            <h5>Fields marked * are required. Text in the "Message" field will be shown to respondents upon submission.</h5>
            <br>
            {{ form|crispy }}
            <br>
            <h4>Add desired number of questions</h4>
            <h5>Notes are for your own use and will not be visible to respondents</h5>
            <br>
            {{ question_formset|crispy }}
            <input type="submit" value="Save" />
        </form>
    </div>
</div>
<br>

{% endblock content %}

templates/dashboard.html
{% extends 'base.html' %}

{% block content %}
{% for quiz in object_list %}
<div class="card" style="width: 35em;margin:0 auto;">
    <div class="card-header" style="width: 35em;margin:0 auto;">
        <h2><a href="{% url 'quizreview' quiz.pk %}">{{ quiz.title }}</a></h2>
    </div>
    <div class="card-body" style="width: 35em;margin:0 auto;">  
        <p>{{ quiz.date_created }}</p>
        <h4>Directions and introductory text:</h4>
        <p>{{ quiz.directions_and_introductory_text|truncatewords:50 }}</p>
        <h4>Primary source text:</h4>
        <p>{{ quiz.primary_source_text|truncatewords:50 }}</p>
        <p><a href="{% url 'quiztake' quiz.pk %}">Link to take quiz</a></p>
        <p>{% url 'quiztake' quiz.pk %}</p>
        {% if quiz.quizresponse_set.count == 1 %}
            <p><a href="{% url 'quizresponses' quiz.pk %}">View 1 response</a></p>
        {% elif quiz.quizresponse_set.count == 0 %}
            <p>No responses have been submitted yet.</p>
        {% else %}
            <p><a href="{% url 'quizresponses' quiz.pk %}">View {{ quiz.quizresponse_set.count }} responses</a></p>
        {% endif %}
    </div>
    <div class="card-footer text-center text-muted" style="width: 35em;margin:0 auto;">
        <a href="{% url 'quizedit' quiz.pk %}">Edit</a> | <a href="{% url 'quizdelete' quiz.pk %}">Delete</a>
    </div>
</div>
<br>
{% endfor %}
{% endblock content %}

templates/home.html
{% extends 'base.html' %}

{% block content %}
<div class="row">
    <h2>A quiz app designed with historians in mind.</h2> 
</div>

{% endblock content %}

templates/quizdelete.html
{% extends 'base.html' %}

{% block content %}
<div class="card" style="width: 45em;margin:0 auto;">
    <div class="card-header">
        <h1>Delete Quiz</h1>
    </div>
<br>
    <div class="card-body text-center">
    <form action="" method="post">{% csrf_token %}
        <h2>Are you sure you want to delete <br> "<a href="{% url 'quizreview' quiz.pk %}">{{ quiz.title }}</a>"?</h2>
        <br>
        <p>Last updated: {{ quiz.date_created }}</p>
        <p>Number of questions: {{ quiz.question_set.count }}</p>
        <br>
        {% if quiz.quizresponse_set.count == 0 %}
            <h3>No responses have been submitted yet.</h3>
        {% elif quiz.quizresponse_set.count == 1 %}
            <h3>This will also delete <a href="{% url 'quizresponses' quiz.pk %}">1 response</a>.</h3>
        {% else %}
            <h3>This will also delete <a href="{% url 'quizresponses' quiz.pk %}">{{ quiz.quizresponse_set.count }} responses</a>.</h3>
        {% endif %}
        <br>
        <input type="submit" value="Confirm Deletion" />
        <br>
        <br>
        <p>This action cannot be undone.</p>
    </form>
    </div>
</div>
<br>
{% endblock content %}

templates/quizedit.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}

<div class="card" style="width: 55em;margin:0 auto;">
    <div class="card-header">
        <h1>Editing "<a href="{% url 'quizreview' quiz.pk %}">{{ quiz.title }}</a>"</h1>
    </div>
    <div class="card-body">
        {% if quiz.quizresponse_set.count == 0 %}
            <h3>No responses have been submitted yet.</h3>
        {% elif quiz.quizresponse_set.count == 1 %}
            <h3>There is already <a href="{% url 'quizresponses' quiz.pk %}">1 response</a>. Are you sure you want to make changes anyway?</h3>
        {% else %}
            <h3>There are already <a href="{% url 'quizresponses' quiz.pk %}">{{ quiz.quizresponse_set.count }} responses</a>. Are you sure you want to make changes anyway?</h3>
        {% endif %}
    </div>
</div>
<br>
<div class="card" style="width: 55em;margin:0 auto;">
    <div class="card-body">
        <form action="" method="post">{% csrf_token %}
            {% csrf_token %}
            <h5>Fields marked * are required. Text in the "Message" field will be shown to respondents upon submission.</h5>
            <br>
            {{ form|crispy }}
            <br>
            <h4>Add desired number of questions</h4>
            <h5>Notes are for your own use and will not be visible to respondents</h5>
            <br>
            {{ question_formset|crispy }}
            <input type="submit" value="Update" />
        </form>
    </div>
</div>
<br>
{% endblock content %}

templates/quizrespondents.html
{% extends 'base.html' %}

{% block content %}
<div class="card" style="width: 55em;margin:0 auto;">
    <div class="card-header">
        <h2><a href="{% url 'quizreview' quiz.pk %}">{{ quiz.title }}</a></h2>
    </div>
    <div class ="card-body">
        <p><a href="{% url 'quizresponses' quiz.pk %}">View by question instead</a></p>
        <p><a href="{% url 'quiztake' quiz.pk %}">Link to take quiz</a></p>
        <p>{% url 'quiztake' quiz.pk %}</p>
    </div>
</div>
<br>
<div class="card" style="width: 55em;margin:0 auto;">
    <div class ="card-body">
        <h3>Date created:</h3>
        <p>{{ quiz.date_created }}</p>
        <h3>Directions and introductory text:</h3>
        <p>{{ quiz.directions_and_introductory_text }}</p>
        <h3>Primary source text:</h3>
        <p>{{ quiz.primary_source_text }}</p>
    </div>
</div>
<br>
<div class="card" style="width: 55em;margin:0 auto;">
    <div class ="card-header">
        <h3>Number of questions: {{ quiz.question_set.count }}</h3>
    </div>
</div>
<br>
        {% for question in quiz.question_set.all %}
            <div class="card" style="width: 55em;margin:0 auto;">
                <div class="card-header">
                    <h3>Question {{ forloop.counter }}</h3>
                </div>
                <div class="card-body">
                    <h4>Question text:</h4>
                    <p>{{ question.question_text }}</p>
                    <br>
                    <h4>Notes for question:</h4>
                    <p>{{ question.notes_for_question }}</p>
                </div>
            </div>
            <br>
        {% endfor %}
<div class="card" style="width: 55em;margin:0 auto;">
    <div class ="card-header">
        <h3>Number of responses: {{ quiz.quizresponse_set.count }}</h3>
    </div>
</div>
<br>
        {% for respondent in quiz.quizresponse_set.all %}
        <div class="card" style="width: 55em;margin:0 auto;">
            <div class="card-header">
                <h4>{{ forloop.counter }}. {{ respondent.name }} | {{ respondent.id_number }} | {{ respondent.attempt_date }}</h4>
            </div>
            <br>
            <div class="card-body">    
                    <ol>
                    {% for response in respondent.questionresponse_set.all %}
                        <li>{{ response.question.question_text }}<br><br>{{ response.response_text }}<br><br></li>
                    {% endfor %}
                    </ol>
            </div>
        </div>
        <br>
        {% endfor %}
    </div>

    


{% endblock content %}

templates/quizresponses.html
{% extends 'base.html' %}

{% block content %}
<div class="card" style="width: 55em;margin:0 auto;">
    <div class="card-header">
        <h2><a href="{% url 'quizreview' quiz.pk %}">{{ quiz.title }}</a></h2>
    </div>
    <div class="card-body">
        <p><a href="{% url 'quizrespondents' quiz.pk %}">View by respondent instead</a></p>
        <p><a href="{% url 'quiztake' quiz.pk %}">Link to take quiz</a></p>
        <p>{% url 'quiztake' quiz.pk %}</p>
    </div>
</div>
<br>
<div class="card" style="width: 55em;margin:0 auto;">
    <div class="card-body">
        <h3>Date created:</h3>
        <p>{{ quiz.date_created }}</p>
        <h3>Directions and introductory text:</h3>
        <p>{{ quiz.directions_and_introductory_text }}</p>
        <h3>Primary source text:</h3>
        <p>{{ quiz.primary_source_text }}</p>
    </div>
</div>
<br>
<div class="card" style="width: 55em;margin:0 auto;">
    <div class="card-header">
        <h3>Number of questions: {{ quiz.question_set.count }}</h3>
        <h3>Number of responses: {{ quiz.quizresponse_set.count }}</h3>
    </div>
</div>
<br>
        {% for question in quiz.question_set.all %}
        <div class="card" style="width: 55em;margin:0 auto;">
            <div class="card-header text-center">
                <h3>Question {{ forloop.counter }}</h3>
            </div>
            <div class="card-body">
                <h4>Question text:</h4>
                <p>{{ question.question_text }}</p>
                <h4>Notes for question:</h4>
                <p>{{ question.notes_for_question }}</p>
                <br>
                <h4>Responses:</h4>
                <ol>
                    {% for questionresponse in question.questionresponse_set.all %}
                    <li>{{ questionresponse.quiz_response.name }} | {{ questionresponse.quiz_response.id_number }} | {{ questionresponse.quiz_response.attempt_date }} <br>
                        {{ questionresponse.response_text }}</li><br>
                    {% endfor %}
                </ol>
            </div>
        </div>
        <br>
        {% endfor %}

    


{% endblock content %}

templates/quizreview.html
{% extends 'base.html' %}

{% block content %}
<div class="card" style="width: 55em;margin:0 auto;">
    <div class="card-header">
        <h2>{{ quiz.title }}</h2>
    </div>
    <div class="card-body">
        <p><a href="{% url 'quiztake' quiz.pk %}">Link to take quiz</a></p>
        <p>{% url 'quiztake' quiz.pk %}</p>
        {% if quiz.quizresponse_set.count == 1 %}
            <p><a href="{% url 'quizresponses' quiz.pk %}">View 1 response</a></p>
        {% elif quiz.quizresponse_set.count == 0 %}
            <p>No responses have been submitted yet.</p>
        {% else %}
            <p><a href="{% url 'quizresponses' quiz.pk %}">View {{ quiz.quizresponse_set.count }} responses</a></p>
        {% endif %}
    </div>
    <div class="card-footer text-center text-muted">
        <a href="{% url 'quizedit' quiz.pk %}">Edit</a> | <a href="{% url 'quizdelete' quiz.pk %}">Delete</a>
    </div>
</div>
<br>
<div class="card" style="width: 55em;margin:0 auto;">
    <div class="card-body">
        <h3>Last updated:</h3>
        <p>{{ quiz.date_created }}</p>
        <h3>Directions and introductory text:</h3>
        <p>{{ quiz.directions_and_introductory_text }}</p>
        <h3>Primary source text:</h3>
        <p>{{ quiz.primary_source_text }}</p>
    </div>
</div>
<br>
<div class="card" style="width: 55em;margin:0 auto;">
    <div class="card-header">
        <h3>Number of questions: {{ quiz.question_set.count }}</h3>
    </div>
</div>
<br>
        {% for question in quiz.question_set.all %}
            <div class="card" style="width: 55em;margin:0 auto;">
                <div class="card-header">
                    <h3>Question {{ forloop.counter }}</h3>
                </div>
                <div class="card-body">
                    <h4>Question text:</h4>
                    <p>{{ question.question_text }}</p>
                    <h4>Notes for question (only visible to you):</h4>
                    <p>{{ question.notes_for_question }}</p>
                </div>
            </div>
            <br>
        {% endfor %}
    </div>
</div>
<br>
<div class="card" style="width: 55em;margin:0 auto;">
    <div class="card-body">
        <h3>Message (seen upon submission of responses):</h3>
        <p>{{ quiz.message }}</p>
    </div>
</div>
<br>

    
{% endblock content %}

templates/quizsubmitted.html
{% extends 'base.html' %}

{% block nav %}
    <h1 class="card-title"><a href="{% url 'home' %}">Quiz App</a></h1>
    {% if user.is_authenticated %}
        <div class="card-text">
            <p>Hi {{ user.username }}! | <a href="{% url 'dashboard' %}">View your quizzes</a> | <a href="{% url 'createnew' %}">+ New quiz</a> | <a href="{% url 'logout' %}">Log out</a></p>
        </div>
    {% endif %} 
{% endblock nav %}

{% block content %}

<div class="card" style="width: 45em;margin:0 auto;">
    <div class="card-header">
        <h2>Your responses have been submitted</h2>
    </div>
    {% if quiz.message %}
        <div class="card-body">
            <p>{{ quiz.message }}</p>
        </div>
    {% endif %}
</div> 
<br>

{% if user.is_authenticated %}
    <div class="card" style="width: 45em;margin:0 auto;">
        <div class="card-title">
            <h3>Note! Responses will not be associated with your account or username</h3>
        </div>
{% endif %}
    <div class="card-body text-center">
        {% if quiz.author == request.user and request.user.is_authenticated %}
            {% if quiz.quizresponse_set.count == 1 %}
                <h4><a href="{% url 'quizresponses' quiz.pk %}">View 1 response</a> | <a href="{% url 'quizreview' quiz.pk %}">Review this quiz</a></h4>
            {% else %}
                <h4><a href="{% url 'quizresponses' quiz.pk %}">View {{ quiz.quizresponse_set.count }} responses</a>  | <a href="{% url 'quizreview' quiz.pk %}">Review this quiz</a></h4>
            {% endif %}
        </div>
    </div>
    <br>
        {% endif %}


{% endblock content %}

templates/signup.html
{% extends 'base.html' %}

{% block content %}
<div class="card" style="width: 45em;margin:0 auto;">
    <div class="card-header">
        <h2>Sign Up</h2>
    </div>
    <div class="card-body">
        <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Sign Up</button>
        </form>
    </div>
</div>
<br>
{% endblock content %}

templates/takequiz.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}


{% block nav %}
<h1 class="card-title"><a href="{% url 'home' %}">Quiz App</a></h1>
    {% if user.is_authenticated %}
        <div class="card-text">
            <p>Hi {{ user.username }}! | <a href="{% url 'dashboard' %}">View your quizzes</a> | <a href="{% url 'createnew' %}">+ New quiz</a> | <a href="{% url 'logout' %}">Log out</a></p>
        </div>
    {% endif %} 
{% endblock nav %}

{% block content %}
    {% if user.is_authenticated %}
        <div class="card" style="width: 55em;margin:0 auto;">
            <div class="card-body text-center">
                <h4>Note! Responses will not be associated with your account or username</h4>
    {% endif %}
    {% if quiz.author == request.user and request.user.is_authenticated %}
        {% if quiz.quizresponse_set.count == 0 %}
            <h5>There are no responses yet | <a href="{% url 'quizreview' quiz.pk %}">Review this quiz</a></h5>
        {% elif quiz.quizresponse_set.count == 1 %}
            <h5><a href="{% url 'quizresponses' quiz.pk %}">View 1 response</a> | <a href="{% url 'quizreview' quiz.pk %}">Review this quiz</a></h5>
        {% else %}
            <h5><a href="{% url 'quizresponses' quiz.pk %}">View {{ quiz.quizresponse_set.count }} responses</a> | <a href="{% url 'quizreview' quiz.pk %}">Review this quiz</a></h5>
        {% endif %}
            </div>
        </div>
    <br>
    {% else %}
            </div>
        </div>
    <br>
    {% endif %}
<div class="card" style="width: 55em;margin:0 auto;">
    <div class="card-header">
        <h1>{{ quiz.title }}</h1>
    </div>
    <div class="card-body">
        <h3>Directions and introductory text</h3>
        <p>{{ quiz.directions_and_introductory_text }}</p>
        <h3>Primary source text</h3>
        <p>{{ quiz.primary_source_text }}</p>
    </div>
</div>
<br>
<div class="card" style="width: 55em;margin:0 auto;">
    <div class="card-body">
        <form action="{% url 'quiztake' quiz_id=quiz.id %}" method="post">
            {% csrf_token %}
            <h3>Your information</h3>
            {{ quiz_response_form|crispy }}
    </div>
</div>
<br>
<div class="card" style="width: 55em;margin:0 auto;">
    <div class="card-body">
            {{ question_response_formset.management_form }}
            {% for form, question in questions_and_responses %}
                <h3>Question {{ forloop.counter }}</h3>
                <h4>{{ question.question_text }}</h4>
                {{ form|crispy }}
            {% endfor %}
            <input type="submit" value="Save" />
        </form>
    </div>
</div>
<br>
{% endblock content %}